name: Sync GitHub to Gitee

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Update Content"
      - "Issues"
    types: [completed]

concurrency:
  group: sync-gitee-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
          # SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          source-repo: https://github.com/abgox/abyss.git
          destination-repo: git@gitee.com:abgox/abyss.git
